### ISSUE TITLE
Dont have GPU

### ISSUE THREAD

**Issue by hurmaeht** [zcemycl/Matlab-GAN#11]
![image](https://user-images.githubusercontent.com/67607001/162298317-194e3fdb-18de-455a-a4c6-f44291883d9e.png)

Hello, I wanted to use the CycleGAN but it keeps saying that the CUDA Driver is unable to load and that the GPU Driver needs to be updated or reinstalled. I checked my laptop's GPU and it is Intel(R) UHD Graphics 620. I am slightly confused as to how to make it work if I don't have nvcuda.dll installed. I even tried installing nvcuda.dll but that also didn't seem to work. Please help me out here. How do I make this work if I don't have a GPU. or how to install a GPU on my computer to make this work.

**Comment by zcemycl** [comment]
@hurmaeht intel integrated chip is not a gpu. Please learn what your hardware is, intel is definitely not cuda.

**Comment by hurmaeht** [comment]
hey @zcemycl could you tell me what I should do to use only my laptop I don't have GPU so what should I do . is there a way to run the code just for testing purposes on my laptop . Like some code to negate the GPU Usage?

**Comment by zcemycl** [comment]
Remove every use of gpu array function. It should work.

The gpuArray function is used to put parameters weights data into gpu memory. So if you remove it, it should work for cpu and ram.

But you should have enough ram for the task.
