### ISSUE TITLE
negate the GPU Usage?

### ISSUE THREAD

**Issue by hurmaeht** [zcemycl/Matlab-GAN#12]
hey @zcemycl could you tell me what I should do to use only my laptop I don't have GPU so what should I do . is there a way to run the code just for testing purposes on my laptop . Like some code to negate the GPU Usage?

_Originally posted by @hurmaeht in https://github.com/zcemycl/Matlab-GAN/issues/11#issuecomment-1094355355_

**Comment by zcemycl** [comment]
Remove every use of gpu array function. It should work.

The gpuArray function is used to put parameters weights data into gpu memory. So if you remove it, it should work for cpu and ram.

But you should have enough ram for the training.

**Comment by zcemycl** [comment]
@hurmaeht please star the repo if it helps :)
