### ISSUE TITLE
Pix2Pix implementation: Bug in the Generator?

### ISSUE THREAD

**Issue by jlherraiz** [zcemycl/Matlab-GAN#2]
First of all, thanks for the codes.

I think that the upsampling part of the Generator of the Pix2Pix code has a couple of issues. The order of the batchnorm and relu are permuted, and the u1 layer has no relu layer defined.
I have tested it with the "right" order and it works much better. Here is the code (with the changes in bold):

 u1=dltranspconv(d7,params.TCW1,params.TCb1,'Stride',2,'Cropping','same');
 u1=batchnormwrap(u1,params,st,7);
 **u1=relu(u1);**
 u1=cat(3,u1,d6);
 
 exstattran = 'u%d = dltranspconv(u%d,params.TCW%d,params.TCb%d,"Stride",2,"Cropping","same");';
 exstatrelu = 'u%d = relu(u%d);';
 exstatbatch2='[u%d,st] = batchnormwrap(u%d,params,st,%d);'; 
 exstatcat =  'u%d=cat(3,u%d,d%d);';
 for i = 2:7
    eval(sprintf(exstattran,i,i-1,i,i));
    if i ~= 7 
        **eval(sprintf(exstatbatch2,i,i,6+i));
        eval(sprintf(exstatrelu,i,i));**
        eval(sprintf(exstatcat,i,i,7-i));
    end
 end
 dly = tanh(u7);
end

**Comment by zcemycl** [comment]
@jlherraiz 
OK. Thank you for the enhancement. I will take a look.
