### ISSUE TITLE
How to save a model.

### ISSUE THREAD

**Issue by songport** [zcemycl/Matlab-GAN#6]
Hello.
Thanks for these nice codes.
Normally we do have checkpoints and model to save to a file.
1. I want to know how to save the model.
    Is it good to save the paramGen and paramDis? and if it is then how to use as a model.
2 .And also I want to know how to test pix2pix.m to a specific image file.
Thanks in advance.

**Comment by zcemycl** [comment]
@songport 
1. You can save the parameters via `save` function in matlab. Just take a look on functions `function [dly,st] = Discriminator(dlx,params,st)` and `function [paramsDis,stDis] = InitializeDis(settings,df)` in `PIX2PIX.m`. `params` are the weights of the network, and `st` are the states of the batch norm. 
2.  To test `PIX2PIX.m`, please take a look for file `LoadFacadeDatabase.m` given in the same pix2pix folder. Change the path. If you want to test on other dataset (but not the facade one), please remember you have to provide data which shows the image translation between a real image and a conditional image.
