### ISSUE TITLE
Although the function gpdl store the array on GPU, the code doesn’t run on the GPU.

### ISSUE THREAD

**Issue by momo-love** [zcemycl/Matlab-GAN#8]
Hello,thanks for your code.  Although the function gpdl store the array on GPU, the code doesn’t run on the GPU.

**Comment by zcemycl** [comment]
@momo-love i think you have a misconception of how codes work. You cannot have entire codes running on gpu, this is not my code problem, you should then ask matlab.

But they will answer you the same. You should understand how code is executed. Nothing is fully relied on gpu. Go to learn some c++ memory allocation etc. They will answer your question.
