### ISSUE TITLE
With cycleGAN, the center is black even after huge epoch.

### ISSUE THREAD

**Issue by ApplePomme** [zcemycl/Matlab-GAN#9]
The center is black even after huge epoch with cycleGAN.

Original code without any modification.

Hope someone can point out my running errors.

![black_center](https://user-images.githubusercontent.com/91695114/135512525-5e9d8ce6-cc48-40e4-9b5a-78f09e47dab2.jpg)

**Comment by zcemycl** [comment]
@ApplePomme If i remember correctly, GAN variants do not do well when you are overtraining it. Try training it under 60 epochs, and with less than batch size of 8.

Unlike image recognition network, GAN performance does not get improved with too much epoch and larger batch size.
